---
apiVersion: v1
kind: Namespace
metadata:
  name: opencspm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: opencspm
automountServiceAccountToken: false  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencspm
  namespace: opencspm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opencspm
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opencspm
  namespace: opencspm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencspm
subjects:
- kind: ServiceAccount
  name: opencspm
  namespace: opencspm
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: opencspm-exporter
  namespace: opencspm
spec:
  concurrencyPolicy: Forbid
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: opencspm
          containers:
          - name: opencspm
            image: gcr.io/opencspm/k8s-cai-exporter:v0.1.6
            env:
            - name: "GCS_BUCKET_NAME"
              value: "darkbit-collection-us-cspm"
            - name: "GCS_BUCKET_FOLDER"
              value: "k8s"
          restartPolicy: Never
