---
- name: Cloud Asset Inventory
  location: gcs://bucket-acme-8765/cai
  status: 1
- name: Kubernetes Sync Inventory
  location: gcs://bucket-acme-8765/k8s
  status: 0
- name: Demo Kubernetes Inventory
  location: file://200924_cai.json
  status: 0
